// Archivo: equipos.js
var DATOS_EQUIPOS = {
    "central": { color: "#F3D83E", escudo: "https://i.imgur.com/g2QZOoB.png" },
    "platense": { color: "#473219", escudo: "https://i.imgur.com/sdHWE4G.png" },
    "racing": { color: "#009BDB", escudo: "https://i.imgur.com/W60CG4W.png" },
    "river": { color: "#E2211C", escudo: "https://i.imgur.com/UB6tl2G.png" },
    "san lorenzo": { color: "#212D4B", escudo: "https://i.imgur.com/iD4h0GV.png" },
    "sarmiento": { color: "#3A6639", escudo: "https://i.imgur.com/MR5im1i.png" },
    "talleres": { color: "#283253", escudo: "https://i.imgur.com/Mpyw7Lz.png" },
    "tigre": { color: "#024084", escudo: "https://i.imgur.com/WkRqhtu.png" },
    "union": { color: "#BF0C13", escudo: "https://i.imgur.com/13P015b.png" },
    "aldosivi": { color: "#E7C607", escudo: "https://i.imgur.com/C9GbGca.png" },
    "argentinos": { color: "#E11E34", escudo: "https://i.imgur.com/80C0fM4.png" },
    "atletico tucuman": { color: "#80A6D2", escudo: "https://i.imgur.com/DeFuzDK.png" },
    "banfield": { color: "#427936", escudo: "https://i.imgur.com/2YEK8KI.png" },
    "barracas": { color: "#D3150C", escudo: "https://i.imgur.com/JROeQms.png" },
    "belgrano": { color: "#3A9CD0", escudo: "https://i.imgur.com/IcEtoAk.png" },
    "boca": { color: "#00438D", escudo: "https://i.imgur.com/q6eUQnN.png" },
    "central cordoba": { color: "#333333", escudo: "https://i.imgur.com/MTET7SZ.png" },
    "defensa y justicia": { color: "#007A3E", escudo: "https://i.imgur.com/k71hkAx.png" },
    "estudiantes lp": { color: "#B61722", escudo: "https://i.imgur.com/FUp6O2e.png" },
    "estudiantes rc": { color: "#008BD2", escudo: "https://i.imgur.com/Z4nykRf.png" },
    "gimnasia lp": { color: "#193A67", escudo: "https://i.imgur.com/UYcDpxX.png" },
    "gimnasia mendoza": { color: "#262626", escudo: "https://i.imgur.com/9kE1oyP.png" },
    "huracan": { color: "#A81417", escudo: "https://i.imgur.com/ft4kqdj.png" },
    "independiente": { color: "#BF0811", escudo: "https://i.imgur.com/5tYaaXi.png" },
    "independiente riv": { color: "#2C3064", escudo: "https://i.imgur.com/aG80jkP.png" },
    "instituto": { color: "#E21B2C", escudo: "https://i.imgur.com/qHdISrt.png" },
    "lanus": { color: "#7B202C", escudo: "https://i.imgur.com/6yIG5B3.png" },
    "newells": { color: "#BF0811", escudo: "https://i.imgur.com/XbtSw5L.png" },
    "velez": { color: "#3562A6", escudo: "https://i.imgur.com/sOZpFdu.png" },
    "riestra": { color: "#282828", escudo: "https://i.imgur.com/RE8WToc.png" },
};